add MIDI start/continue/stop signals sendable from a MIDI Module
jean-emmanuel/mentat pull request #2
Opened 2024-04-08 19:24 UTC by Houston4444

J'ai besoin de pouvoir envoyer les messages MIDI start et stop pour mes greffons [plujain ramp live](https://github.com/Houston4444/plujain-ramp), c'était pas possible visiblement, avec ça ça l'est. J'ai aussi ajouté 'continue', parce que c'était dans la même veine.

2024-04-08 20:55 UTC, jean-emmanuel requested changes
À part le commentaire que j'ai mis ça me semble ok, merci pour la contribution !

2024-04-08 20:55 UTC, jean-emmanuel commented on mentat/midi.py
> +        osc['args'] = []
Ça ne me semble pas correct, le retour d'une valeur nulle est attendu ici dans les cas non supportés : https://github.com/jean-emmanuel/mentat/blob/master/mentat/engine.py#L611-L621

2024-04-09 16:16 UTC, Houston4444 commented
j'ai modifié la branche, ça doit résoudre l'erreur.

2024-04-14 09:35 UTC, jean-emmanuel commented
Looks good to me, sending and receiving seems to work fine, thank you :)

2024-04-14 09:36 UTC, merged

2024-04-14 09:42 UTC, jean-emmanuel commented
Par contre, je suis revenu sur ton changement de "==" vers "is", ce n'est pas tout à fait correct / sensé de le faire pour des nombres, et la micro optimisation potentielle ne me semble pas le justifier.

2024-04-14 10:44 UTC, Houston4444 commented
> Impeccable, ça marche en envoi et en reception, merci :).

Parfait, merci.

> Par contre, je suis revenu sur ton changement de "==" vers "is", ce n'est pas tout à fait correct / sensé de le faire pour des nombres, et la micro optimisation potentielle ne me semble pas le justifier.

Bon, c'est vraiment trivial tout ça, je m'en fiche pas mal, l'influence doit être bien minime, c'est juste à titre informatif:
* les SEQ_EVENT_* sont de type alsaseq.Constant (surclasse de `int`), du coup le 'is' me paraît pas déconnant dans ce cas, comme pour les IntEnum
* quand on fait `mtype in (SEQ_EVENT_PITCHBEND, SEQ_EVENT_PGMCHANGE)` ça revient exactement à `mtype is SEQ_EVENT_PITCHBEND or mtype is SEQ_EVENT_PGMCHANGE`, donc ça me semble plus cohérent.

2024-04-14 11:24 UTC, jean-emmanuel commented
Un peu de lecture plus tard, je reviens sur ce que j'ai dis, merci !